version: '3'
services:
  web:
    build: .
    ports:
     - 8080

  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8090:80